# __13) Numpy Library__

#### NumPy is a Python library.

#### NumPy is used for working with arrays.

#### NumPy is short for "Numerical Python".

# ⮩ Creating a Numpy Array

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# ⮩ What is an Array?
### _An array is a special variable, which can hold more than one value at a time._  
### _Arrays are a fundamental data structure, and an important part of most programming languages. In Python, they are containers which are able to store more than one item at the same time. Specifically, they are an ordered collection of elements with every value being of the same data types._

# ⮩ What is NumPy?
#### _NumPy is a Python library used for working with arrays._

#### _It also has functions for working in domain of linear algebra, fourier transform, and matrices._

#### _NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely._

#### _NumPy stands for Numerical Python._

# ⮩ Why Use NumPy?
#### _In Python we have lists that serve the purpose of arrays, but they are slow to process._

#### _NumPy aims to provide an array object that is up to 50x faster than traditional Python lists._

#### _The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy._

#### _Arrays are very frequently used in data science, where speed and resources are very important._

# ⮩ Why is NumPy Faster Than Lists?
#### _NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently._

#### _This behavior is called locality of reference in computer science._

#### _This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures._



# ⮩ Which Language is NumPy written in?
### _NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++._



# ⮩ Installation of NumPy
#### _If you have Python and PIP already installed on a system, then installation of NumPy is very easy._

#### C:\Users\Your Name > pip install numpy

# Import NumPy
#### _Once NumPy is installed, import it in your applications by adding the import keyword :_

## import numpy

In [2]:
lst = [1,2,3,4,5]
print(lst)
print(type(lst))

[1, 2, 3, 4, 5]
<class 'list'>


In [3]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# NumPy as np
### _NumPy is usually imported under the np alias._

In [3]:
import numpy as np

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# ⮩ Checking NumPy Version
### _The version string is stored under __version__ attribute._

In [4]:
np.__version__

'1.26.4'

In [5]:
import numpy as np

print(np.__version__)

1.26.4


# Create a NumPy ndarray Object
#### _NumPy is used to work with arrays. The array object in NumPy is called ndarray._

#### _We can create a NumPy ndarray object by using the __array() function__._

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


# ➩➩  Dimensions in Arrays
#### _A dimension in arrays is one level of array depth (nested arrays)._

# ⮩  0-D Arrays
#### _0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array._

In [8]:
import numpy as np

arr = np.array(42)
print(arr)

42


# ⮩ 1-D Arrays
#### _An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array._

#### _These are the most common and basic arrays._

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


# ⮩ 2-D Arrays
#### _An array that has 1-D arrays as its elements is called a 2-D array._

#### _These are often used to represent matrix or 2nd order tensors._

In [8]:
                             # 2d array
import numpy as np
arr2 = [[1,2,3], [4,5,6]]        # if we dont write 'np.array' even after importing numpy, it will return list object
print(arr2)
print(type(arr2))

[[1, 2, 3], [4, 5, 6]]
<class 'list'>


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


# ⮩ 3-D arrays
#### _An array that has 2-D arrays (matrices) as its elements is called 3-D array._

#### _These are often used to represent a 3rd order tensor._
#### _Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6 :_

In [6]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [5]:
import numpy as np                                     # 3d array

arr3 = ([[[1,2,3], [4,5,6]],  [[1,2,3], [4,5,6]],  [[1,2,3], [4,5,6]]])

print(arr3)
print(type(arr3))

[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]
<class 'list'>


In [8]:
arr3[0][0][0]

1

# Check Number of Dimensions?
#### _NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have._

In [11]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# ⮩ Higher Dimensional Arrays
#### _An array can have any number of dimensions._
#### _When the array is created, you can define the number of dimensions by using the ndmin argument._

In [9]:
                                              # creating a nd array
newarr = np.array([1,2,3,4,5], ndmin=5)
newarr

array([[[[[1, 2, 3, 4, 5]]]]])

In [10]:
 # how to check dimensions of an array

newarr.ndim

5

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


#### _In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array._

# ➩➩ Access Array Elements == Array Indexing
#### _Array indexing is the same as accessing an array element._
#### _You can access an array element by referring to its index number._
#### _The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc._

In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr[1])

2


In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


# ⮩ Access 2-D Arrays
#### _To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element._
#### _Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column._

In [18]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [19]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


# ⮩ Access 3-D Arrays
#### _To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element._

In [20]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


# ⮩ Negative Indexing
#### _Use negative indexing to access an array from the end._

In [21]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# ➩➩ Slicing arrays
#### _Slicing in python means taking elements from one given index to another given index._
##### _We pass slice instead of index like this: [start:end]._

##### _We can also define the step, like this: [start:end:step]._

##### _If we don't pass start its considered 0_

##### _If we don't pass end its considered length of array in that dimension_

##### _If we don't pass step its considered 1_

In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [24]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


# ⮩  Negative Slicing
#### _Use the minus operator to refer to an index from the end :_

In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


# STEP
##### _Use the step value to determine the step of the slicing :_

In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


# ⮩  Slicing 2-D Arrays

In [28]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [29]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [30]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
# NumPy Data Types
By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
integer - used to represent integer numbers. e.g. -1, -2, -3
float - used to represent real numbers. e.g. 1.2, 42.32
boolean - used to represent True or False.
complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

# ➩➩ Data Types in NumPy
#### _NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc._
#### _Below is a list of all data types in NumPy and the characters used to represent them._

i - integer  
b - boolean   
u - unsigned integer  
f - float   
c - complex float  
m - timedelta   
M - datetime   
O - object   
S - string   
U - unicode string   
V - fixed chunk of memory for other type ( void )

# ⮩ Checking the Data Type of an Array
#### _The NumPy array object has a property called dtype that returns the data type of the array :_

In [31]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [32]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


# ⮩ Creating Arrays With a Defined Data Type
#### _We use the __array() function__ to create arrays, this function can take an optional argument : dtype that allows us to define the expected data type of the array elements :_

In [33]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [34]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# ⮩ What if a Value Can Not Be Converted ?
#### _If a type is given in which elements can't be casted then NumPy will raise a ValueError._

In [35]:
import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

# ⮩ Converting Data Type on Existing Arrays
#### _The best way to change the data type of an existing array, is to make a copy of the array with the __astype() method.___
#### _The __astype() function__ creates a copy of the array, and allows you to specify the data type as a parameter._
#### _The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer._

In [36]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [37]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [38]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


# ➩➩➩ The Difference Between Copy and View
#### _The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array._
#### _The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy._
#### _The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view._

# ⮩ COPY :

In [13]:
arr = np.array([1,2,3,4,5])

copyarr = arr.copy()
copyarr

array([1, 2, 3, 4, 5])

In [7]:
arr = np.array([1,2,3,4,5])

copyarr = arr.copy()

copyarr[0] = 100
print(copyarr)

[100   2   3   4   5]


In [39]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


# ⮩ VIEW :

In [8]:
import numpy as np

# view
arr = np.array([1,2,3,4,5])
viewarr = arr.view()
viewarr

array([1, 2, 3, 4, 5])

In [4]:
viewarr[0] = 100
print(viewarr)

[100   2   3   4   5]


In [40]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [41]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


# ➩➩  Shape of an Array
#### _The shape of an array is the number of elements in each dimension._
#### _NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements._

In [10]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [43]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# ➩➩ Reshaping arrays
#### _Reshaping means changing the shape of an array._
#### _The shape of an array is the number of elements in each dimension._
#### _By reshaping we can add or remove dimensions or change number of elements in each dimension._
#### _Reshape From 1-D to 2-D_

In [44]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# ⮩  Reshape From 1-D to 3-D

In [11]:
# reshaping
array1 = np.array ([3,5,7,9,8,6,7,5])
new1 = array1.reshape(4,2)
new1

array([[3, 5],
       [7, 9],
       [8, 6],
       [7, 5]])

In [10]:
new1 = array1.reshape(2,4 )
new1

array([[3, 5, 7, 9],
       [8, 6, 7, 5]])

In [17]:
new1.shape

(2, 4)

In [13]:
new1 = array1.reshape(3,2)
new1

ValueError: cannot reshape array of size 8 into shape (3,2)

In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [18]:
arr8 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newar = arr8.reshape(2, 3, 2)
newar

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# ⮩ Can We Reshape Into any Shape?
#### _Yes, as long as the elements required for reshaping are equal in both shapes._

#### _We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3 x 3 = 9 elements._

In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)
print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [19]:
import numpy as np            # returned array is a copy or a view:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4))

[[1 2 3 4]
 [5 6 7 8]]


# ⮩ Unknown Dimension
#### _You are allowed to have one "unknown" dimension._

#### _Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method._

#### _Pass -1 as the value, and NumPy will calculate this number for you._

In [48]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# ➩ Flattening the arrays
#### _Flattening array means converting a multidimensional array into a 1D array._
##### _We can use reshape(-1) to do this._

In [49]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [20]:
arr9 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarray = arr9.reshape(2, 3, 2)

arr1d = newarray.flatten()
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# ➩ Iterating Arrays
#### _Iterating means going through elements one by one._
#### _As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python._
#### _If we iterate on a 1-D array it will go through each element one by one._

In [50]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


# ⮩ Iterating 2-D Arrays
#### _In a 2-D array it will go through all the rows._

In [51]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [21]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
         print(y)


1
2
3
4
5
6


In [22]:
                                      # 2d array
ar = [[1,2,3], [4,5,6]]

for i in ar:
    print(i)

[1, 2, 3]
[4, 5, 6]


# ⮩ Iterating 3-D Arrays
#### _In a 3-D array it will go through all the 2-D arrays._

In [23]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [24]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# ➩ Iterating Arrays Using nditer()
#### _The function __nditer()__ is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

# ⮩  Iterating on Each Scalar Element
#### _In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality._

In [22]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [55]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


# ➩  Iterating Array With Different Data Types
#### _We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating._
#### _NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered']._

In [25]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


# ➩ Iterating With Different Step Size
#### _We can use filtering and followed by iteration._

In [48]:
[i for i in range(1,8)]      # comprehnsion

[1, 2, 3, 4, 5, 6, 7]

In [57]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


# ➩ Enumerated Iteration Using ndenumerate()
#### _Enumeration means mentioning sequence number of somethings one by one._
#### _Sometimes we require corresponding index of the element while iterating, the __ndenumerate() method__ can be used for those usecases._

In [58]:
import numpy as np     # 1D ARRAY

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [59]:
import numpy as np    # 2D ARRAY

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)


(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# ➩➩➩  Joining NumPy Arrays
#### _Joining means putting contents of two or more arrays in a single array._
### _In SQL we join tables based on a key, whereas in NumPy we join arrays by axes._

#### _We pass a sequence of arrays that we want to join to the  concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0._

# ⮩ concatenate() function

In [23]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [60]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [61]:
import numpy as np               # Join two 2-D arrays along rows (axis=1):

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [24]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# ➩ Joining Arrays Using Stack Functions
#### _Stacking is same as concatenation, the only difference is that stacking is done along a new axis._
#### _We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking._
#### _We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0._

In [2]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


# ⮩  Stacking Along Rows
#### _NumPy provides a helper function: hstack() to stack along rows._

In [63]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


# ⮩  Stacking Along Columns
#### _NumPy provides a helper function : __vstack()__  to stack along columns._

In [65]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


# ⮩  Stacking Along Height (depth)
#### _NumPy provides a helper function : __dstack()__ to stack along height, which is the same as depth._

In [66]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# ➩ Splitting NumPy Arrays
#### _Splitting is reverse operation of Joining._
#### _Joining merges multiple arrays into one and Splitting breaks one array into multiple._
#### _We use __array_split()__ for splitting arrays, we pass it the array we want to split and the number of splits._

In [67]:
import numpy as np     # Split the array in 3 parts:

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [68]:
import numpy as np               # Split the array in 4 parts:

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


# ⮩ Split Into Arrays
#### _The return value of the array_split() method is an array containing each of the split as an array._
#### _If you split an array into 3 arrays, you can access them from the result just like any array element :_

In [69]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


# ⮩  Splitting 2-D Arrays
#### _Use the same syntax when splitting 2-D arrays._
#### _Use the __array_split()__ method, pass in the array you want to split and the number of splits you want to do._

In [70]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [71]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [72]:
# Split the 2-D array into three 2-D arrays along columns.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# ➩ An alternate solution is using hsplit() opposite of hstack()
### _Use the __hsplit()__ method to split the __2-D array__ into __three 2-D arrays__ along columns._

In [73]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


#### __Note :__ Similar alternates to __vstack()__ and __dstack()__ are available as __vsplit()__ and __dsplit()__.

# ➩➩➩ Searching Arrays
#### _You can search an array for a certain value, and return the indexes that get a match._
#### _To search an array, use the __where()__ method._

In [28]:
import numpy as np                # Find the indexes where the value is 4:

arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [27]:
                                             # Find the indexes where the values are even:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [26]:
                                             # Find the indexes where the values are odd:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [25]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [29]:
np.where(arr==2)

(array([1], dtype=int64),)

# ➩➩➩ Sorting Arrays
#### _Sorting means putting elements in an ordered sequence._
#### _Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending._
#### _The NumPy ndarray object has a function called __sort()__ , that will sort a specified array._

In [36]:
import numpy as np

arr1 = np.array([3, 2, 0, 1])
print(np.sort(arr1))

[0 1 2 3]


In [37]:
np.min(arr1)

0

In [38]:
np.max(arr1)

3

In [40]:
np.mean(arr1)

1.5

In [41]:
np.sum(arr1)

6

In [42]:
np.prod(arr1)

0

In [35]:
import numpy as np               # sorting strings

arr2 = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr2))

['apple' 'banana' 'cherry']


In [34]:
import numpy as np              # sorting boolean

arr3 = np.array([True, False, True])
print(np.sort(arr3))

[False  True  True]


In [33]:
lst1 = np.array([4,5,6,7,8,9])
arrr = np.array([[4,5,6],[7,9,8]])

lst1.sort()
np.sort(arrr)

array([[4, 5, 6],
       [7, 8, 9]])

# ⮩  Sorting a 2-D Array
#### _If you use the __sort()__ method on a 2-D array, both arrays will be sorted :_

In [80]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# ➩ Filtering Arrays
#### _Getting some elements out of an existing array and creating a new array out of them is called filtering._
#### _In NumPy, you filter an array using a boolean index list._
#### _--> If the value at an index is __True__ that element is contained in the filtered array,_  
#### _--> if the value at that index is __False__ that element is excluded from the filtered array._

In [81]:
import numpy as np

arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]

print(newarr)

[41 43]


# ⮩ Search Sorted
### _There is a method called __searchsorted()__ which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order._

In [45]:
import numpy as np

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)

print(x)

1


# ⮩ Search From the Right Side
#### _By default the left most index is returned, but we can give __side = 'right'__ to return the right most index instead_.

In [46]:
import numpy as np

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)

2


In [47]:
import numpy as np           # Multiple Values

arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


# ➩ Create a filter array that will return only values higher than 42 :

In [82]:
import numpy as np

arr = np.array([41, 42, 43, 44])
                                      # Create an empty list
filter_arr = []
                                   # go through each element in arr
for element in arr:
                               # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
                    # Create an empty list
filter_arr = []
                    # go through each element in arr
for element in arr:
                       # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

# ➩ Calculating Mean and Standard Deviation :

In [1]:
import numpy as np

data = [10, 12, 15, 11, 13, 16, 14]

mean_value = np.mean(data)
std_dev = np.std(data)

print(f"Mean: {mean_value}")
print(f"Standard Deviation: {std_dev}")

Mean: 13.0
Standard Deviation: 2.0
